misc:
  run_mode: test # Mode to run the network in
  num_points: 99999 # Number of points
  use_gpu: True # If GPU should be used or not
  visualize: False
  index_list: [54]

data:
  dataset: NuScenes_ME # Name of the dataset [StereoKITTI_ME, FlyingThings3D_ME, SemanticKITTI_ME, LidarKITTI_ME, WaymoOpen_ME]
  root: /mnt/cfs/algorithm/chaokang.jiang/3DSFLabeling/Driving_datasets/argoverse/Argoverse2_LiDAR_Raw/ # ./sceneflow_eval_dataset/nuscenes/nuscenes/val
  remove_ground: False # Remove ground by simple thresholding of the height coordinate
  augment_data: False # Augment the data by random rotation and translation
  only_near_points: True # Only consider near points (less than 35m away) [Used in all scene flow algorithms]
  only_front_points: False
  filter_normals: False

test:
  batch_size: 1 # Test batch size
  num_workers: 12 # Num of workers to use for the test data set

hyperparameters:
  box_depth: 4
  box_scale: 1.25
  sigmoid_slope: 8
  epsilon: .02
  background_boost_coeff: 0
  heading_loss_coeff: 1000
  angle_loss_coeff: .25
  mass_loss_coeff: .01
  dim_loss_coeff: 8
  prune_threshold: 100
  confidence_threshold: .85
  seg_threshold: .03
  print_loss: False
  lr: .016
  epochs: 1
  delta_threshold: 0
  cycle: False
  cycle_threshold: 0
  evaluate_train: False